"""clean up pre-alembic schema drift

Revision ID: 1324ee61887c
Revises: 4adb412e452c
Create Date: 2026-07-13 11:44:07.515648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1324ee61887c'
down_revision: Union[str, Sequence[str], None] = '4adb412e452c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Only relevant to databases that went through the old manual
    create_all()/ensure_*() bootstrap before Alembic existed — they may
    still have the dead `notices` table and pre-schema-split index names.
    A fresh database built from the baseline migration never has these,
    so skip entirely rather than erroring on DROP-ing things that were
    never created.
    """
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if "notices" not in inspector.get_table_names(schema="notifications"):
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_notices_created_by_user_id'), table_name='notices', schema='notifications')
    op.drop_index(op.f('ix_notifications_notices_id'), table_name='notices', schema='notifications')
    op.drop_table('notices', schema='notifications')
    op.drop_index(op.f('ix_users_email'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_users_id'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_users_username'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_users_verification_token'), table_name='users', schema='auth')
    op.create_index(op.f('ix_auth_users_email'), 'users', ['email'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_users_id'), 'users', ['id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_users_username'), 'users', ['username'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_users_verification_token'), 'users', ['verification_token'], unique=True, schema='auth')
    op.drop_index(op.f('ix_feedback_messages_id'), table_name='feedback_messages', schema='feedback')
    op.drop_index(op.f('ix_feedback_messages_user_id'), table_name='feedback_messages', schema='feedback')
    op.create_index(op.f('ix_feedback_feedback_messages_id'), 'feedback_messages', ['id'], unique=False, schema='feedback')
    op.create_index(op.f('ix_feedback_feedback_messages_user_id'), 'feedback_messages', ['user_id'], unique=False, schema='feedback')
    op.drop_index(op.f('ix_goal_checkins_check_date'), table_name='goal_checkins', schema='goals')
    op.drop_index(op.f('ix_goal_checkins_goal_id'), table_name='goal_checkins', schema='goals')
    op.drop_index(op.f('ix_goal_checkins_id'), table_name='goal_checkins', schema='goals')
    op.drop_index(op.f('ix_goal_checkins_user_id'), table_name='goal_checkins', schema='goals')
    op.create_index(op.f('ix_goals_goal_checkins_check_date'), 'goal_checkins', ['check_date'], unique=False, schema='goals')
    op.create_index(op.f('ix_goals_goal_checkins_goal_id'), 'goal_checkins', ['goal_id'], unique=False, schema='goals')
    op.create_index(op.f('ix_goals_goal_checkins_id'), 'goal_checkins', ['id'], unique=False, schema='goals')
    op.create_index(op.f('ix_goals_goal_checkins_user_id'), 'goal_checkins', ['user_id'], unique=False, schema='goals')
    op.drop_index(op.f('ix_goal_stages_goal_id'), table_name='goal_stages', schema='goals')
    op.drop_index(op.f('ix_goal_stages_id'), table_name='goal_stages', schema='goals')
    op.create_index(op.f('ix_goals_goal_stages_goal_id'), 'goal_stages', ['goal_id'], unique=False, schema='goals')
    op.create_index(op.f('ix_goals_goal_stages_id'), 'goal_stages', ['id'], unique=False, schema='goals')
    op.drop_index(op.f('ix_goals_id'), table_name='goals', schema='goals')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals', schema='goals')
    op.create_index(op.f('ix_goals_goals_id'), 'goals', ['id'], unique=False, schema='goals')
    op.create_index(op.f('ix_goals_goals_user_id'), 'goals', ['user_id'], unique=False, schema='goals')
    op.drop_index(op.f('ix_notification_recipients_id'), table_name='notification_recipients', schema='notifications')
    op.drop_index(op.f('ix_notification_recipients_notification_id'), table_name='notification_recipients', schema='notifications')
    op.drop_index(op.f('ix_notification_recipients_user_id'), table_name='notification_recipients', schema='notifications')
    op.create_index(op.f('ix_notifications_notification_recipients_id'), 'notification_recipients', ['id'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notification_recipients_notification_id'), 'notification_recipients', ['notification_id'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notification_recipients_user_id'), 'notification_recipients', ['user_id'], unique=False, schema='notifications')
    op.drop_index(op.f('ix_notifications_created_by_user_id'), table_name='notifications', schema='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications', schema='notifications')
    op.create_index(op.f('ix_notifications_notifications_created_by_user_id'), 'notifications', ['created_by_user_id'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notifications_id'), 'notifications', ['id'], unique=False, schema='notifications')
    op.drop_index(op.f('ix_day_settings_day'), table_name='day_settings', schema='planning')
    op.drop_index(op.f('ix_day_settings_id'), table_name='day_settings', schema='planning')
    op.drop_index(op.f('ix_day_settings_user_id'), table_name='day_settings', schema='planning')
    op.create_index(op.f('ix_planning_day_settings_day'), 'day_settings', ['day'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_day_settings_id'), 'day_settings', ['id'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_day_settings_user_id'), 'day_settings', ['user_id'], unique=False, schema='planning')
    op.drop_index(op.f('ix_day_tasks_day'), table_name='day_tasks', schema='planning')
    op.drop_index(op.f('ix_day_tasks_id'), table_name='day_tasks', schema='planning')
    op.drop_index(op.f('ix_day_tasks_order_index'), table_name='day_tasks', schema='planning')
    op.drop_index(op.f('ix_day_tasks_source_week_task_id'), table_name='day_tasks', schema='planning')
    op.drop_index(op.f('ix_day_tasks_user_id'), table_name='day_tasks', schema='planning')
    op.create_index(op.f('ix_planning_day_tasks_day'), 'day_tasks', ['day'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_day_tasks_id'), 'day_tasks', ['id'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_day_tasks_order_index'), 'day_tasks', ['order_index'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_day_tasks_source_inbox_task_id'), 'day_tasks', ['source_inbox_task_id'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_day_tasks_source_week_task_id'), 'day_tasks', ['source_week_task_id'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_day_tasks_user_id'), 'day_tasks', ['user_id'], unique=False, schema='planning')
    op.drop_index(op.f('ix_day_templates_id'), table_name='day_templates', schema='planning')
    op.drop_index(op.f('ix_day_templates_user_id'), table_name='day_templates', schema='planning')
    op.create_index(op.f('ix_planning_day_templates_id'), 'day_templates', ['id'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_day_templates_user_id'), 'day_templates', ['user_id'], unique=False, schema='planning')
    op.drop_index(op.f('ix_inbox_tasks_id'), table_name='inbox_tasks', schema='planning')
    op.drop_index(op.f('ix_inbox_tasks_user_id'), table_name='inbox_tasks', schema='planning')
    op.create_index(op.f('ix_planning_inbox_tasks_id'), 'inbox_tasks', ['id'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_inbox_tasks_user_id'), 'inbox_tasks', ['user_id'], unique=False, schema='planning')
    op.drop_index(op.f('ix_task_categories_id'), table_name='task_categories', schema='planning')
    op.drop_index(op.f('ix_task_categories_key'), table_name='task_categories', schema='planning')
    op.drop_index(op.f('ix_task_categories_user_id'), table_name='task_categories', schema='planning')
    op.create_index(op.f('ix_planning_task_categories_id'), 'task_categories', ['id'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_task_categories_key'), 'task_categories', ['key'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_task_categories_user_id'), 'task_categories', ['user_id'], unique=False, schema='planning')
    op.drop_index(op.f('ix_week_tasks_id'), table_name='week_tasks', schema='planning')
    op.drop_index(op.f('ix_week_tasks_user_id'), table_name='week_tasks', schema='planning')
    op.create_index(op.f('ix_planning_week_tasks_id'), 'week_tasks', ['id'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_week_tasks_user_id'), 'week_tasks', ['user_id'], unique=False, schema='planning')
    op.drop_index(op.f('ix_week_templates_id'), table_name='week_templates', schema='planning')
    op.drop_index(op.f('ix_week_templates_user_id'), table_name='week_templates', schema='planning')
    op.create_index(op.f('ix_planning_week_templates_id'), 'week_templates', ['id'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_week_templates_user_id'), 'week_templates', ['user_id'], unique=False, schema='planning')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planning_week_templates_user_id'), table_name='week_templates', schema='planning')
    op.drop_index(op.f('ix_planning_week_templates_id'), table_name='week_templates', schema='planning')
    op.create_index(op.f('ix_week_templates_user_id'), 'week_templates', ['user_id'], unique=False, schema='planning')
    op.create_index(op.f('ix_week_templates_id'), 'week_templates', ['id'], unique=False, schema='planning')
    op.drop_index(op.f('ix_planning_week_tasks_user_id'), table_name='week_tasks', schema='planning')
    op.drop_index(op.f('ix_planning_week_tasks_id'), table_name='week_tasks', schema='planning')
    op.create_index(op.f('ix_week_tasks_user_id'), 'week_tasks', ['user_id'], unique=False, schema='planning')
    op.create_index(op.f('ix_week_tasks_id'), 'week_tasks', ['id'], unique=False, schema='planning')
    op.drop_index(op.f('ix_planning_task_categories_user_id'), table_name='task_categories', schema='planning')
    op.drop_index(op.f('ix_planning_task_categories_key'), table_name='task_categories', schema='planning')
    op.drop_index(op.f('ix_planning_task_categories_id'), table_name='task_categories', schema='planning')
    op.create_index(op.f('ix_task_categories_user_id'), 'task_categories', ['user_id'], unique=False, schema='planning')
    op.create_index(op.f('ix_task_categories_key'), 'task_categories', ['key'], unique=False, schema='planning')
    op.create_index(op.f('ix_task_categories_id'), 'task_categories', ['id'], unique=False, schema='planning')
    op.drop_index(op.f('ix_planning_inbox_tasks_user_id'), table_name='inbox_tasks', schema='planning')
    op.drop_index(op.f('ix_planning_inbox_tasks_id'), table_name='inbox_tasks', schema='planning')
    op.create_index(op.f('ix_inbox_tasks_user_id'), 'inbox_tasks', ['user_id'], unique=False, schema='planning')
    op.create_index(op.f('ix_inbox_tasks_id'), 'inbox_tasks', ['id'], unique=False, schema='planning')
    op.drop_index(op.f('ix_planning_day_templates_user_id'), table_name='day_templates', schema='planning')
    op.drop_index(op.f('ix_planning_day_templates_id'), table_name='day_templates', schema='planning')
    op.create_index(op.f('ix_day_templates_user_id'), 'day_templates', ['user_id'], unique=False, schema='planning')
    op.create_index(op.f('ix_day_templates_id'), 'day_templates', ['id'], unique=False, schema='planning')
    op.drop_index(op.f('ix_planning_day_tasks_user_id'), table_name='day_tasks', schema='planning')
    op.drop_index(op.f('ix_planning_day_tasks_source_week_task_id'), table_name='day_tasks', schema='planning')
    op.drop_index(op.f('ix_planning_day_tasks_source_inbox_task_id'), table_name='day_tasks', schema='planning')
    op.drop_index(op.f('ix_planning_day_tasks_order_index'), table_name='day_tasks', schema='planning')
    op.drop_index(op.f('ix_planning_day_tasks_id'), table_name='day_tasks', schema='planning')
    op.drop_index(op.f('ix_planning_day_tasks_day'), table_name='day_tasks', schema='planning')
    op.create_index(op.f('ix_day_tasks_user_id'), 'day_tasks', ['user_id'], unique=False, schema='planning')
    op.create_index(op.f('ix_day_tasks_source_week_task_id'), 'day_tasks', ['source_week_task_id'], unique=False, schema='planning')
    op.create_index(op.f('ix_day_tasks_order_index'), 'day_tasks', ['order_index'], unique=False, schema='planning')
    op.create_index(op.f('ix_day_tasks_id'), 'day_tasks', ['id'], unique=False, schema='planning')
    op.create_index(op.f('ix_day_tasks_day'), 'day_tasks', ['day'], unique=False, schema='planning')
    op.drop_index(op.f('ix_planning_day_settings_user_id'), table_name='day_settings', schema='planning')
    op.drop_index(op.f('ix_planning_day_settings_id'), table_name='day_settings', schema='planning')
    op.drop_index(op.f('ix_planning_day_settings_day'), table_name='day_settings', schema='planning')
    op.create_index(op.f('ix_day_settings_user_id'), 'day_settings', ['user_id'], unique=False, schema='planning')
    op.create_index(op.f('ix_day_settings_id'), 'day_settings', ['id'], unique=False, schema='planning')
    op.create_index(op.f('ix_day_settings_day'), 'day_settings', ['day'], unique=False, schema='planning')
    op.drop_index(op.f('ix_notifications_notifications_id'), table_name='notifications', schema='notifications')
    op.drop_index(op.f('ix_notifications_notifications_created_by_user_id'), table_name='notifications', schema='notifications')
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_created_by_user_id'), 'notifications', ['created_by_user_id'], unique=False, schema='notifications')
    op.drop_index(op.f('ix_notifications_notification_recipients_user_id'), table_name='notification_recipients', schema='notifications')
    op.drop_index(op.f('ix_notifications_notification_recipients_notification_id'), table_name='notification_recipients', schema='notifications')
    op.drop_index(op.f('ix_notifications_notification_recipients_id'), table_name='notification_recipients', schema='notifications')
    op.create_index(op.f('ix_notification_recipients_user_id'), 'notification_recipients', ['user_id'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notification_recipients_notification_id'), 'notification_recipients', ['notification_id'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notification_recipients_id'), 'notification_recipients', ['id'], unique=False, schema='notifications')
    op.drop_index(op.f('ix_goals_goals_user_id'), table_name='goals', schema='goals')
    op.drop_index(op.f('ix_goals_goals_id'), table_name='goals', schema='goals')
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False, schema='goals')
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False, schema='goals')
    op.drop_index(op.f('ix_goals_goal_stages_id'), table_name='goal_stages', schema='goals')
    op.drop_index(op.f('ix_goals_goal_stages_goal_id'), table_name='goal_stages', schema='goals')
    op.create_index(op.f('ix_goal_stages_id'), 'goal_stages', ['id'], unique=False, schema='goals')
    op.create_index(op.f('ix_goal_stages_goal_id'), 'goal_stages', ['goal_id'], unique=False, schema='goals')
    op.drop_index(op.f('ix_goals_goal_checkins_user_id'), table_name='goal_checkins', schema='goals')
    op.drop_index(op.f('ix_goals_goal_checkins_id'), table_name='goal_checkins', schema='goals')
    op.drop_index(op.f('ix_goals_goal_checkins_goal_id'), table_name='goal_checkins', schema='goals')
    op.drop_index(op.f('ix_goals_goal_checkins_check_date'), table_name='goal_checkins', schema='goals')
    op.create_index(op.f('ix_goal_checkins_user_id'), 'goal_checkins', ['user_id'], unique=False, schema='goals')
    op.create_index(op.f('ix_goal_checkins_id'), 'goal_checkins', ['id'], unique=False, schema='goals')
    op.create_index(op.f('ix_goal_checkins_goal_id'), 'goal_checkins', ['goal_id'], unique=False, schema='goals')
    op.create_index(op.f('ix_goal_checkins_check_date'), 'goal_checkins', ['check_date'], unique=False, schema='goals')
    op.drop_index(op.f('ix_feedback_feedback_messages_user_id'), table_name='feedback_messages', schema='feedback')
    op.drop_index(op.f('ix_feedback_feedback_messages_id'), table_name='feedback_messages', schema='feedback')
    op.create_index(op.f('ix_feedback_messages_user_id'), 'feedback_messages', ['user_id'], unique=False, schema='feedback')
    op.create_index(op.f('ix_feedback_messages_id'), 'feedback_messages', ['id'], unique=False, schema='feedback')
    op.drop_index(op.f('ix_auth_users_verification_token'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_username'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_id'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_email'), table_name='users', schema='auth')
    op.create_index(op.f('ix_users_verification_token'), 'users', ['verification_token'], unique=True, schema='auth')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True, schema='auth')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False, schema='auth')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True, schema='auth')
    op.create_table('notices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['auth.users.id'], name=op.f('notices_created_by_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notices_pkey')),
    schema='notifications'
    )
    op.create_index(op.f('ix_notifications_notices_id'), 'notices', ['id'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notices_created_by_user_id'), 'notices', ['created_by_user_id'], unique=False, schema='notifications')
    # ### end Alembic commands ###
