"""align pre-alembic prod schema with models

Revision ID: 3907d6d53071
Revises: 1324ee61887c
Create Date: 2026-07-13 20:36:24.782565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3907d6d53071'
down_revision: Union[str, Sequence[str], None] = '1324ee61887c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Only relevant to the production database, which was originally converted
    from SQLite by pgloader: every integer landed as BIGINT, every string as
    TEXT, NOT NULL constraints were lost and indexes kept pgloader's
    idx_<oid>_* names. Databases built from the baseline migration (or by the
    old create_all() bootstrap) already match the models, so skip there —
    BIGINT users.id is the telltale of the pgloader heritage.
    """
    bind = op.get_bind()
    users_id_type = next(
        col["type"]
        for col in sa.inspect(bind).get_columns("users", schema="auth")
        if col["name"] == "id"
    )
    if not isinstance(users_id_type, sa.BigInteger):
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='auth')
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               schema='auth')
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               schema='auth')
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               schema='auth')
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               schema='auth')
    op.alter_column('users', 'verification_token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               schema='auth')
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text("'user'::text"),
               schema='auth')
    op.drop_index(op.f('idx_16615_ix_users_email'), table_name='users', schema='auth')
    op.drop_index(op.f('idx_16615_ix_users_username'), table_name='users', schema='auth')
    op.create_index(op.f('ix_auth_users_email'), 'users', ['email'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_users_id'), 'users', ['id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_users_username'), 'users', ['username'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_users_verification_token'), 'users', ['verification_token'], unique=True, schema='auth')
    op.alter_column('feedback_messages', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='feedback')
    op.alter_column('feedback_messages', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True,
               schema='feedback')
    op.alter_column('feedback_messages', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               schema='feedback')
    op.alter_column('feedback_messages', 'feedback_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               schema='feedback')
    op.alter_column('feedback_messages', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               schema='feedback')
    op.alter_column('feedback_messages', 'contact',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               schema='feedback')
    op.alter_column('feedback_messages', 'message',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='feedback')
    op.alter_column('feedback_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               schema='feedback')
    op.alter_column('feedback_messages', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               schema='feedback')
    op.alter_column('feedback_messages', 'developer_replied_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               schema='feedback')
    op.drop_index(op.f('idx_16651_ix_feedback_messages_user_id'), table_name='feedback_messages', schema='feedback')
    op.create_index(op.f('ix_feedback_feedback_messages_id'), 'feedback_messages', ['id'], unique=False, schema='feedback')
    op.create_index(op.f('ix_feedback_feedback_messages_user_id'), 'feedback_messages', ['user_id'], unique=False, schema='feedback')
    op.alter_column('goal_checkins', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='goals')
    op.alter_column('goal_checkins', 'goal_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               schema='goals')
    op.alter_column('goal_checkins', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               schema='goals')
    op.alter_column('goal_checkins', 'check_date',
               existing_type=sa.DATE(),
               nullable=False,
               schema='goals')
    op.alter_column('goal_checkins', 'done',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='goals')
    op.alter_column('goal_checkins', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               schema='goals')
    op.drop_index(op.f('idx_16678_ix_goal_checkins_check_date'), table_name='goal_checkins', schema='goals')
    op.drop_index(op.f('idx_16678_ix_goal_checkins_goal_id'), table_name='goal_checkins', schema='goals')
    op.drop_index(op.f('idx_16678_ix_goal_checkins_user_id'), table_name='goal_checkins', schema='goals')
    op.create_index(op.f('ix_goals_goal_checkins_check_date'), 'goal_checkins', ['check_date'], unique=False, schema='goals')
    op.create_index(op.f('ix_goals_goal_checkins_goal_id'), 'goal_checkins', ['goal_id'], unique=False, schema='goals')
    op.create_index(op.f('ix_goals_goal_checkins_id'), 'goal_checkins', ['id'], unique=False, schema='goals')
    op.create_index(op.f('ix_goals_goal_checkins_user_id'), 'goal_checkins', ['user_id'], unique=False, schema='goals')
    op.alter_column('goal_stages', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='goals')
    op.alter_column('goal_stages', 'goal_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               schema='goals')
    op.alter_column('goal_stages', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               schema='goals')
    op.alter_column('goal_stages', 'done',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='goals')
    op.alter_column('goal_stages', 'order_index',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               schema='goals')
    op.drop_index(op.f('idx_16664_ix_goal_stages_goal_id'), table_name='goal_stages', schema='goals')
    op.create_index(op.f('ix_goals_goal_stages_goal_id'), 'goal_stages', ['goal_id'], unique=False, schema='goals')
    op.create_index(op.f('ix_goals_goal_stages_id'), 'goal_stages', ['id'], unique=False, schema='goals')
    op.alter_column('goals', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='goals')
    op.alter_column('goals', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               schema='goals')
    op.alter_column('goals', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               schema='goals')
    op.alter_column('goals', 'color',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               schema='goals')
    op.alter_column('goals', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               schema='goals')
    op.alter_column('goals', 'order_index',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               schema='goals')
    op.alter_column('goals', 'goal_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text("'one_time'::text"),
               schema='goals')
    op.alter_column('goals', 'repeat_unit',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               schema='goals')
    op.alter_column('goals', 'has_stages',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               schema='goals')
    op.alter_column('goals', 'schedule_mode',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               schema='goals')
    op.alter_column('goals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='goals')
    op.drop_index(op.f('idx_16656_ix_goals_user_id'), table_name='goals', schema='goals')
    op.create_index(op.f('ix_goals_goals_id'), 'goals', ['id'], unique=False, schema='goals')
    op.create_index(op.f('ix_goals_goals_user_id'), 'goals', ['user_id'], unique=False, schema='goals')
    op.alter_column('notification_recipients', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='notifications')
    op.alter_column('notification_recipients', 'notification_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               schema='notifications')
    op.alter_column('notification_recipients', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               schema='notifications')
    op.alter_column('notification_recipients', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='notifications')
    op.drop_index(op.f('idx_16675_ix_notification_recipients_notification_id'), table_name='notification_recipients', schema='notifications')
    op.drop_index(op.f('idx_16675_ix_notification_recipients_user_id'), table_name='notification_recipients', schema='notifications')
    op.create_index(op.f('ix_notifications_notification_recipients_id'), 'notification_recipients', ['id'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notification_recipients_notification_id'), 'notification_recipients', ['notification_id'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notification_recipients_user_id'), 'notification_recipients', ['user_id'], unique=False, schema='notifications')
    op.alter_column('notifications', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='notifications')
    op.alter_column('notifications', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               schema='notifications')
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='notifications')
    op.alter_column('notifications', 'created_by_user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True,
               schema='notifications')
    op.alter_column('notifications', 'audience_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               schema='notifications')
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='notifications')
    op.drop_index(op.f('idx_16669_ix_notifications_created_by_user_id'), table_name='notifications', schema='notifications')
    op.create_index(op.f('ix_notifications_notifications_created_by_user_id'), 'notifications', ['created_by_user_id'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notifications_id'), 'notifications', ['id'], unique=False, schema='notifications')
    op.alter_column('day_settings', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='planning')
    op.alter_column('day_settings', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               schema='planning')
    op.alter_column('day_settings', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=False,
               schema='planning')
    op.drop_index(op.f('idx_16643_ix_day_settings_day'), table_name='day_settings', schema='planning')
    op.drop_index(op.f('idx_16643_ix_day_settings_user_id'), table_name='day_settings', schema='planning')
    op.create_index(op.f('ix_planning_day_settings_day'), 'day_settings', ['day'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_day_settings_id'), 'day_settings', ['id'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_day_settings_user_id'), 'day_settings', ['user_id'], unique=False, schema='planning')
    op.alter_column('day_tasks', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='planning')
    op.alter_column('day_tasks', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               schema='planning')
    op.alter_column('day_tasks', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               schema='planning')
    op.alter_column('day_tasks', 'duration_min',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True,
               schema='planning')
    op.alter_column('day_tasks', 'priority',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               schema='planning')
    op.alter_column('day_tasks', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               schema='planning')
    op.alter_column('day_tasks', 'status',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True,
               schema='planning')
    op.alter_column('day_tasks', 'order_index',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               schema='planning')
    op.alter_column('day_tasks', 'source_week_task_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True,
               schema='planning')
    op.drop_index(op.f('idx_16638_ix_day_tasks_day'), table_name='day_tasks', schema='planning')
    op.drop_index(op.f('idx_16638_ix_day_tasks_order_index'), table_name='day_tasks', schema='planning')
    op.drop_index(op.f('idx_16638_ix_day_tasks_user_id'), table_name='day_tasks', schema='planning')
    op.create_index(op.f('ix_planning_day_tasks_day'), 'day_tasks', ['day'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_day_tasks_id'), 'day_tasks', ['id'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_day_tasks_order_index'), 'day_tasks', ['order_index'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_day_tasks_source_inbox_task_id'), 'day_tasks', ['source_inbox_task_id'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_day_tasks_source_week_task_id'), 'day_tasks', ['source_week_task_id'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_day_tasks_user_id'), 'day_tasks', ['user_id'], unique=False, schema='planning')
    op.create_foreign_key(None, 'day_tasks', 'week_tasks', ['source_week_task_id'], ['id'], source_schema='planning', referent_schema='planning')
    op.alter_column('day_templates', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='planning')
    op.alter_column('day_templates', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               schema='planning')
    op.alter_column('day_templates', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               schema='planning')
    op.alter_column('day_templates', 'color',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               schema='planning')
    op.alter_column('day_templates', 'tasks_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               schema='planning')
    op.drop_index(op.f('idx_16628_ix_day_templates_user_id'), table_name='day_templates', schema='planning')
    op.create_index(op.f('ix_planning_day_templates_id'), 'day_templates', ['id'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_day_templates_user_id'), 'day_templates', ['user_id'], unique=False, schema='planning')
    op.alter_column('task_categories', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='planning')
    op.alter_column('task_categories', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               schema='planning')
    op.alter_column('task_categories', 'key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               schema='planning')
    op.alter_column('task_categories', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               schema='planning')
    op.alter_column('task_categories', 'color',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               schema='planning')
    op.alter_column('task_categories', 'icon',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text("'tag'::text"),
               schema='planning')
    op.drop_index(op.f('idx_16622_ix_task_categories_key'), table_name='task_categories', schema='planning')
    op.drop_index(op.f('idx_16622_ix_task_categories_user_id'), table_name='task_categories', schema='planning')
    op.create_index(op.f('ix_planning_task_categories_id'), 'task_categories', ['id'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_task_categories_key'), 'task_categories', ['key'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_task_categories_user_id'), 'task_categories', ['user_id'], unique=False, schema='planning')
    op.alter_column('week_tasks', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='planning')
    op.alter_column('week_tasks', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               schema='planning')
    op.alter_column('week_tasks', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               schema='planning')
    op.alter_column('week_tasks', 'start_date',
               existing_type=sa.DATE(),
               nullable=False,
               schema='planning')
    op.alter_column('week_tasks', 'end_date',
               existing_type=sa.DATE(),
               nullable=False,
               schema='planning')
    op.alter_column('week_tasks', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               schema='planning')
    op.alter_column('week_tasks', 'status',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True,
               schema='planning')
    op.alter_column('week_tasks', 'order_index',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               schema='planning')
    op.alter_column('week_tasks', 'task_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               schema='planning')
    op.alter_column('week_tasks', 'volume_value',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True,
               schema='planning')
    op.drop_index(op.f('idx_16646_ix_week_tasks_user_id'), table_name='week_tasks', schema='planning')
    op.create_index(op.f('ix_planning_week_tasks_id'), 'week_tasks', ['id'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_week_tasks_user_id'), 'week_tasks', ['user_id'], unique=False, schema='planning')
    op.alter_column('week_templates', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='planning')
    op.alter_column('week_templates', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               schema='planning')
    op.alter_column('week_templates', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               schema='planning')
    op.alter_column('week_templates', 'color',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               schema='planning')
    op.alter_column('week_templates', 'tasks_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               schema='planning')
    op.drop_index(op.f('idx_16633_ix_week_templates_user_id'), table_name='week_templates', schema='planning')
    op.create_index(op.f('ix_planning_week_templates_id'), 'week_templates', ['id'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_week_templates_user_id'), 'week_templates', ['user_id'], unique=False, schema='planning')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planning_week_templates_user_id'), table_name='week_templates', schema='planning')
    op.drop_index(op.f('ix_planning_week_templates_id'), table_name='week_templates', schema='planning')
    op.create_index(op.f('idx_16633_ix_week_templates_user_id'), 'week_templates', ['user_id'], unique=False, schema='planning')
    op.alter_column('week_templates', 'tasks_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               schema='planning')
    op.alter_column('week_templates', 'color',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               schema='planning')
    op.alter_column('week_templates', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               schema='planning')
    op.alter_column('week_templates', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               schema='planning')
    op.alter_column('week_templates', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='planning')
    op.drop_index(op.f('ix_planning_week_tasks_user_id'), table_name='week_tasks', schema='planning')
    op.drop_index(op.f('ix_planning_week_tasks_id'), table_name='week_tasks', schema='planning')
    op.create_index(op.f('idx_16646_ix_week_tasks_user_id'), 'week_tasks', ['user_id'], unique=False, schema='planning')
    op.alter_column('week_tasks', 'volume_value',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True,
               schema='planning')
    op.alter_column('week_tasks', 'task_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='planning')
    op.alter_column('week_tasks', 'order_index',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               schema='planning')
    op.alter_column('week_tasks', 'status',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True,
               schema='planning')
    op.alter_column('week_tasks', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='planning')
    op.alter_column('week_tasks', 'end_date',
               existing_type=sa.DATE(),
               nullable=True,
               schema='planning')
    op.alter_column('week_tasks', 'start_date',
               existing_type=sa.DATE(),
               nullable=True,
               schema='planning')
    op.alter_column('week_tasks', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               schema='planning')
    op.alter_column('week_tasks', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               schema='planning')
    op.alter_column('week_tasks', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='planning')
    op.drop_index(op.f('ix_planning_task_categories_user_id'), table_name='task_categories', schema='planning')
    op.drop_index(op.f('ix_planning_task_categories_key'), table_name='task_categories', schema='planning')
    op.drop_index(op.f('ix_planning_task_categories_id'), table_name='task_categories', schema='planning')
    op.create_index(op.f('idx_16622_ix_task_categories_user_id'), 'task_categories', ['user_id'], unique=False, schema='planning')
    op.create_index(op.f('idx_16622_ix_task_categories_key'), 'task_categories', ['key'], unique=False, schema='planning')
    op.alter_column('task_categories', 'icon',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'tag'::text"),
               schema='planning')
    op.alter_column('task_categories', 'color',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               schema='planning')
    op.alter_column('task_categories', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               schema='planning')
    op.alter_column('task_categories', 'key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               schema='planning')
    op.alter_column('task_categories', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               schema='planning')
    op.alter_column('task_categories', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='planning')
    op.drop_index(op.f('ix_planning_day_templates_user_id'), table_name='day_templates', schema='planning')
    op.drop_index(op.f('ix_planning_day_templates_id'), table_name='day_templates', schema='planning')
    op.create_index(op.f('idx_16628_ix_day_templates_user_id'), 'day_templates', ['user_id'], unique=False, schema='planning')
    op.alter_column('day_templates', 'tasks_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               schema='planning')
    op.alter_column('day_templates', 'color',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               schema='planning')
    op.alter_column('day_templates', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               schema='planning')
    op.alter_column('day_templates', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               schema='planning')
    op.alter_column('day_templates', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='planning')
    op.drop_constraint(None, 'day_tasks', schema='planning', type_='foreignkey')
    op.drop_index(op.f('ix_planning_day_tasks_user_id'), table_name='day_tasks', schema='planning')
    op.drop_index(op.f('ix_planning_day_tasks_source_week_task_id'), table_name='day_tasks', schema='planning')
    op.drop_index(op.f('ix_planning_day_tasks_source_inbox_task_id'), table_name='day_tasks', schema='planning')
    op.drop_index(op.f('ix_planning_day_tasks_order_index'), table_name='day_tasks', schema='planning')
    op.drop_index(op.f('ix_planning_day_tasks_id'), table_name='day_tasks', schema='planning')
    op.drop_index(op.f('ix_planning_day_tasks_day'), table_name='day_tasks', schema='planning')
    op.create_index(op.f('idx_16638_ix_day_tasks_user_id'), 'day_tasks', ['user_id'], unique=False, schema='planning')
    op.create_index(op.f('idx_16638_ix_day_tasks_order_index'), 'day_tasks', ['order_index'], unique=False, schema='planning')
    op.create_index(op.f('idx_16638_ix_day_tasks_day'), 'day_tasks', ['day'], unique=False, schema='planning')
    op.alter_column('day_tasks', 'source_week_task_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True,
               schema='planning')
    op.alter_column('day_tasks', 'order_index',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               schema='planning')
    op.alter_column('day_tasks', 'status',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True,
               schema='planning')
    op.alter_column('day_tasks', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='planning')
    op.alter_column('day_tasks', 'priority',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='planning')
    op.alter_column('day_tasks', 'duration_min',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True,
               schema='planning')
    op.alter_column('day_tasks', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               schema='planning')
    op.alter_column('day_tasks', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               schema='planning')
    op.alter_column('day_tasks', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='planning')
    op.drop_index(op.f('ix_planning_day_settings_user_id'), table_name='day_settings', schema='planning')
    op.drop_index(op.f('ix_planning_day_settings_id'), table_name='day_settings', schema='planning')
    op.drop_index(op.f('ix_planning_day_settings_day'), table_name='day_settings', schema='planning')
    op.create_index(op.f('idx_16643_ix_day_settings_user_id'), 'day_settings', ['user_id'], unique=False, schema='planning')
    op.create_index(op.f('idx_16643_ix_day_settings_day'), 'day_settings', ['day'], unique=False, schema='planning')
    op.alter_column('day_settings', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=True,
               schema='planning')
    op.alter_column('day_settings', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               schema='planning')
    op.alter_column('day_settings', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='planning')
    op.drop_index(op.f('ix_notifications_notifications_id'), table_name='notifications', schema='notifications')
    op.drop_index(op.f('ix_notifications_notifications_created_by_user_id'), table_name='notifications', schema='notifications')
    op.create_index(op.f('idx_16669_ix_notifications_created_by_user_id'), 'notifications', ['created_by_user_id'], unique=False, schema='notifications')
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='notifications')
    op.alter_column('notifications', 'audience_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               schema='notifications')
    op.alter_column('notifications', 'created_by_user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True,
               schema='notifications')
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='notifications')
    op.alter_column('notifications', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               schema='notifications')
    op.alter_column('notifications', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='notifications')
    op.drop_index(op.f('ix_notifications_notification_recipients_user_id'), table_name='notification_recipients', schema='notifications')
    op.drop_index(op.f('ix_notifications_notification_recipients_notification_id'), table_name='notification_recipients', schema='notifications')
    op.drop_index(op.f('ix_notifications_notification_recipients_id'), table_name='notification_recipients', schema='notifications')
    op.create_index(op.f('idx_16675_ix_notification_recipients_user_id'), 'notification_recipients', ['user_id'], unique=False, schema='notifications')
    op.create_index(op.f('idx_16675_ix_notification_recipients_notification_id'), 'notification_recipients', ['notification_id'], unique=False, schema='notifications')
    op.alter_column('notification_recipients', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='notifications')
    op.alter_column('notification_recipients', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               schema='notifications')
    op.alter_column('notification_recipients', 'notification_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               schema='notifications')
    op.alter_column('notification_recipients', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='notifications')
    op.drop_index(op.f('ix_goals_goals_user_id'), table_name='goals', schema='goals')
    op.drop_index(op.f('ix_goals_goals_id'), table_name='goals', schema='goals')
    op.create_index(op.f('idx_16656_ix_goals_user_id'), 'goals', ['user_id'], unique=False, schema='goals')
    op.alter_column('goals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='goals')
    op.alter_column('goals', 'schedule_mode',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='goals')
    op.alter_column('goals', 'has_stages',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'),
               schema='goals')
    op.alter_column('goals', 'repeat_unit',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='goals')
    op.alter_column('goals', 'goal_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'one_time'::text"),
               schema='goals')
    op.alter_column('goals', 'order_index',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               schema='goals')
    op.alter_column('goals', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               schema='goals')
    op.alter_column('goals', 'color',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               schema='goals')
    op.alter_column('goals', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               schema='goals')
    op.alter_column('goals', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               schema='goals')
    op.alter_column('goals', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='goals')
    op.drop_index(op.f('ix_goals_goal_stages_id'), table_name='goal_stages', schema='goals')
    op.drop_index(op.f('ix_goals_goal_stages_goal_id'), table_name='goal_stages', schema='goals')
    op.create_index(op.f('idx_16664_ix_goal_stages_goal_id'), 'goal_stages', ['goal_id'], unique=False, schema='goals')
    op.alter_column('goal_stages', 'order_index',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               schema='goals')
    op.alter_column('goal_stages', 'done',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='goals')
    op.alter_column('goal_stages', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               schema='goals')
    op.alter_column('goal_stages', 'goal_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               schema='goals')
    op.alter_column('goal_stages', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='goals')
    op.drop_index(op.f('ix_goals_goal_checkins_user_id'), table_name='goal_checkins', schema='goals')
    op.drop_index(op.f('ix_goals_goal_checkins_id'), table_name='goal_checkins', schema='goals')
    op.drop_index(op.f('ix_goals_goal_checkins_goal_id'), table_name='goal_checkins', schema='goals')
    op.drop_index(op.f('ix_goals_goal_checkins_check_date'), table_name='goal_checkins', schema='goals')
    op.create_index(op.f('idx_16678_ix_goal_checkins_user_id'), 'goal_checkins', ['user_id'], unique=False, schema='goals')
    op.create_index(op.f('idx_16678_ix_goal_checkins_goal_id'), 'goal_checkins', ['goal_id'], unique=False, schema='goals')
    op.create_index(op.f('idx_16678_ix_goal_checkins_check_date'), 'goal_checkins', ['check_date'], unique=False, schema='goals')
    op.alter_column('goal_checkins', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               schema='goals')
    op.alter_column('goal_checkins', 'done',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='goals')
    op.alter_column('goal_checkins', 'check_date',
               existing_type=sa.DATE(),
               nullable=True,
               schema='goals')
    op.alter_column('goal_checkins', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               schema='goals')
    op.alter_column('goal_checkins', 'goal_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               schema='goals')
    op.alter_column('goal_checkins', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='goals')
    op.drop_index(op.f('ix_feedback_feedback_messages_user_id'), table_name='feedback_messages', schema='feedback')
    op.drop_index(op.f('ix_feedback_feedback_messages_id'), table_name='feedback_messages', schema='feedback')
    op.create_index(op.f('idx_16651_ix_feedback_messages_user_id'), 'feedback_messages', ['user_id'], unique=False, schema='feedback')
    op.alter_column('feedback_messages', 'developer_replied_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               schema='feedback')
    op.alter_column('feedback_messages', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               schema='feedback')
    op.alter_column('feedback_messages', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               schema='feedback')
    op.alter_column('feedback_messages', 'message',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='feedback')
    op.alter_column('feedback_messages', 'contact',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='feedback')
    op.alter_column('feedback_messages', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='feedback')
    op.alter_column('feedback_messages', 'feedback_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               schema='feedback')
    op.alter_column('feedback_messages', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               schema='feedback')
    op.alter_column('feedback_messages', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True,
               schema='feedback')
    op.alter_column('feedback_messages', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='feedback')
    op.drop_index(op.f('ix_auth_users_verification_token'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_username'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_id'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_email'), table_name='users', schema='auth')
    op.create_index(op.f('idx_16615_ix_users_username'), 'users', ['username'], unique=True, schema='auth')
    op.create_index(op.f('idx_16615_ix_users_email'), 'users', ['email'], unique=True, schema='auth')
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'user'::text"),
               schema='auth')
    op.alter_column('users', 'verification_token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='auth')
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'),
               schema='auth')
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               schema='auth')
    op.alter_column('users', 'username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               schema='auth')
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               schema='auth')
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='auth')
    # ### end Alembic commands ###
