"""baseline schema

Revision ID: 4adb412e452c
Revises: 
Create Date: 2026-07-13 11:40:50.880924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4adb412e452c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    for schema in ("auth", "planning", "goals", "notifications", "feedback"):
        op.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema}"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('default_day_start_time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_users_email'), 'users', ['email'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_users_id'), 'users', ['id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_users_username'), 'users', ['username'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_users_verification_token'), 'users', ['verification_token'], unique=True, schema='auth')
    op.create_table('telegram_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=True),
    sa.Column('link_code', sa.String(), nullable=True),
    sa.Column('link_code_expires', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_telegram_links_chat_id'), 'telegram_links', ['chat_id'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_telegram_links_id'), 'telegram_links', ['id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_telegram_links_link_code'), 'telegram_links', ['link_code'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_telegram_links_user_id'), 'telegram_links', ['user_id'], unique=True, schema='auth')
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_user_sessions_id'), 'user_sessions', ['id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_user_sessions_jti'), 'user_sessions', ['jti'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False, schema='auth')
    op.create_table('feedback_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('feedback_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('developer_reply', sa.Text(), nullable=True),
    sa.Column('developer_replied_at', sa.DateTime(), nullable=True),
    sa.Column('screenshots', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='feedback'
    )
    op.create_index(op.f('ix_feedback_feedback_messages_id'), 'feedback_messages', ['id'], unique=False, schema='feedback')
    op.create_index(op.f('ix_feedback_feedback_messages_user_id'), 'feedback_messages', ['user_id'], unique=False, schema='feedback')
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('goal_type', sa.String(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('repeat_unit', sa.String(), nullable=True),
    sa.Column('has_stages', sa.Boolean(), nullable=False),
    sa.Column('schedule_mode', sa.String(), nullable=True),
    sa.Column('category_key', sa.String(), nullable=True),
    sa.Column('is_focus', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='goals'
    )
    op.create_index(op.f('ix_goals_goals_id'), 'goals', ['id'], unique=False, schema='goals')
    op.create_index(op.f('ix_goals_goals_user_id'), 'goals', ['user_id'], unique=False, schema='goals')
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('audience_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='notifications'
    )
    op.create_index(op.f('ix_notifications_notifications_created_by_user_id'), 'notifications', ['created_by_user_id'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notifications_id'), 'notifications', ['id'], unique=False, schema='notifications')
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('remind_at', sa.DateTime(), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='notifications'
    )
    op.create_index(op.f('ix_notifications_reminders_id'), 'reminders', ['id'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_reminders_remind_at'), 'reminders', ['remind_at'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_reminders_sent'), 'reminders', ['sent'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_reminders_user_id'), 'reminders', ['user_id'], unique=False, schema='notifications')
    op.create_table('day_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='planning'
    )
    op.create_index(op.f('ix_planning_day_notes_day'), 'day_notes', ['day'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_day_notes_id'), 'day_notes', ['id'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_day_notes_user_id'), 'day_notes', ['user_id'], unique=False, schema='planning')
    op.create_table('day_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='planning'
    )
    op.create_index(op.f('ix_planning_day_settings_day'), 'day_settings', ['day'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_day_settings_id'), 'day_settings', ['id'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_day_settings_user_id'), 'day_settings', ['user_id'], unique=False, schema='planning')
    op.create_table('day_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('tasks_json', sa.JSON(), nullable=False),
    sa.Column('day_start', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='planning'
    )
    op.create_index(op.f('ix_planning_day_templates_id'), 'day_templates', ['id'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_day_templates_user_id'), 'day_templates', ['user_id'], unique=False, schema='planning')
    op.create_table('inbox_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subtasks', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='planning'
    )
    op.create_index(op.f('ix_planning_inbox_tasks_id'), 'inbox_tasks', ['id'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_inbox_tasks_user_id'), 'inbox_tasks', ['user_id'], unique=False, schema='planning')
    op.create_table('task_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='planning'
    )
    op.create_index(op.f('ix_planning_task_categories_id'), 'task_categories', ['id'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_task_categories_key'), 'task_categories', ['key'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_task_categories_user_id'), 'task_categories', ['user_id'], unique=False, schema='planning')
    op.create_table('week_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('important', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('subtasks', sa.JSON(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=True),
    sa.Column('repeat_days', sa.JSON(), nullable=True),
    sa.Column('volume_value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='planning'
    )
    op.create_index(op.f('ix_planning_week_tasks_id'), 'week_tasks', ['id'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_week_tasks_user_id'), 'week_tasks', ['user_id'], unique=False, schema='planning')
    op.create_table('week_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('tasks_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='planning'
    )
    op.create_index(op.f('ix_planning_week_templates_id'), 'week_templates', ['id'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_week_templates_user_id'), 'week_templates', ['user_id'], unique=False, schema='planning')
    op.create_table('goal_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('check_date', sa.Date(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='goals'
    )
    op.create_index(op.f('ix_goals_goal_checkins_check_date'), 'goal_checkins', ['check_date'], unique=False, schema='goals')
    op.create_index(op.f('ix_goals_goal_checkins_goal_id'), 'goal_checkins', ['goal_id'], unique=False, schema='goals')
    op.create_index(op.f('ix_goals_goal_checkins_id'), 'goal_checkins', ['id'], unique=False, schema='goals')
    op.create_index(op.f('ix_goals_goal_checkins_user_id'), 'goal_checkins', ['user_id'], unique=False, schema='goals')
    op.create_table('goal_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.goals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='goals'
    )
    op.create_index(op.f('ix_goals_goal_stages_goal_id'), 'goal_stages', ['goal_id'], unique=False, schema='goals')
    op.create_index(op.f('ix_goals_goal_stages_id'), 'goal_stages', ['id'], unique=False, schema='goals')
    op.create_table('notification_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.notifications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='notifications'
    )
    op.create_index(op.f('ix_notifications_notification_recipients_id'), 'notification_recipients', ['id'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notification_recipients_notification_id'), 'notification_recipients', ['notification_id'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notification_recipients_user_id'), 'notification_recipients', ['user_id'], unique=False, schema='notifications')
    op.create_table('day_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('subtasks', sa.JSON(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('source_week_task_id', sa.Integer(), nullable=True),
    sa.Column('source_inbox_task_id', sa.Integer(), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_inbox_task_id'], ['planning.inbox_tasks.id'], ),
    sa.ForeignKeyConstraint(['source_week_task_id'], ['planning.week_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='planning'
    )
    op.create_index(op.f('ix_planning_day_tasks_day'), 'day_tasks', ['day'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_day_tasks_id'), 'day_tasks', ['id'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_day_tasks_order_index'), 'day_tasks', ['order_index'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_day_tasks_source_inbox_task_id'), 'day_tasks', ['source_inbox_task_id'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_day_tasks_source_week_task_id'), 'day_tasks', ['source_week_task_id'], unique=False, schema='planning')
    op.create_index(op.f('ix_planning_day_tasks_user_id'), 'day_tasks', ['user_id'], unique=False, schema='planning')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planning_day_tasks_user_id'), table_name='day_tasks', schema='planning')
    op.drop_index(op.f('ix_planning_day_tasks_source_week_task_id'), table_name='day_tasks', schema='planning')
    op.drop_index(op.f('ix_planning_day_tasks_source_inbox_task_id'), table_name='day_tasks', schema='planning')
    op.drop_index(op.f('ix_planning_day_tasks_order_index'), table_name='day_tasks', schema='planning')
    op.drop_index(op.f('ix_planning_day_tasks_id'), table_name='day_tasks', schema='planning')
    op.drop_index(op.f('ix_planning_day_tasks_day'), table_name='day_tasks', schema='planning')
    op.drop_table('day_tasks', schema='planning')
    op.drop_index(op.f('ix_notifications_notification_recipients_user_id'), table_name='notification_recipients', schema='notifications')
    op.drop_index(op.f('ix_notifications_notification_recipients_notification_id'), table_name='notification_recipients', schema='notifications')
    op.drop_index(op.f('ix_notifications_notification_recipients_id'), table_name='notification_recipients', schema='notifications')
    op.drop_table('notification_recipients', schema='notifications')
    op.drop_index(op.f('ix_goals_goal_stages_id'), table_name='goal_stages', schema='goals')
    op.drop_index(op.f('ix_goals_goal_stages_goal_id'), table_name='goal_stages', schema='goals')
    op.drop_table('goal_stages', schema='goals')
    op.drop_index(op.f('ix_goals_goal_checkins_user_id'), table_name='goal_checkins', schema='goals')
    op.drop_index(op.f('ix_goals_goal_checkins_id'), table_name='goal_checkins', schema='goals')
    op.drop_index(op.f('ix_goals_goal_checkins_goal_id'), table_name='goal_checkins', schema='goals')
    op.drop_index(op.f('ix_goals_goal_checkins_check_date'), table_name='goal_checkins', schema='goals')
    op.drop_table('goal_checkins', schema='goals')
    op.drop_index(op.f('ix_planning_week_templates_user_id'), table_name='week_templates', schema='planning')
    op.drop_index(op.f('ix_planning_week_templates_id'), table_name='week_templates', schema='planning')
    op.drop_table('week_templates', schema='planning')
    op.drop_index(op.f('ix_planning_week_tasks_user_id'), table_name='week_tasks', schema='planning')
    op.drop_index(op.f('ix_planning_week_tasks_id'), table_name='week_tasks', schema='planning')
    op.drop_table('week_tasks', schema='planning')
    op.drop_index(op.f('ix_planning_task_categories_user_id'), table_name='task_categories', schema='planning')
    op.drop_index(op.f('ix_planning_task_categories_key'), table_name='task_categories', schema='planning')
    op.drop_index(op.f('ix_planning_task_categories_id'), table_name='task_categories', schema='planning')
    op.drop_table('task_categories', schema='planning')
    op.drop_index(op.f('ix_planning_inbox_tasks_user_id'), table_name='inbox_tasks', schema='planning')
    op.drop_index(op.f('ix_planning_inbox_tasks_id'), table_name='inbox_tasks', schema='planning')
    op.drop_table('inbox_tasks', schema='planning')
    op.drop_index(op.f('ix_planning_day_templates_user_id'), table_name='day_templates', schema='planning')
    op.drop_index(op.f('ix_planning_day_templates_id'), table_name='day_templates', schema='planning')
    op.drop_table('day_templates', schema='planning')
    op.drop_index(op.f('ix_planning_day_settings_user_id'), table_name='day_settings', schema='planning')
    op.drop_index(op.f('ix_planning_day_settings_id'), table_name='day_settings', schema='planning')
    op.drop_index(op.f('ix_planning_day_settings_day'), table_name='day_settings', schema='planning')
    op.drop_table('day_settings', schema='planning')
    op.drop_index(op.f('ix_planning_day_notes_user_id'), table_name='day_notes', schema='planning')
    op.drop_index(op.f('ix_planning_day_notes_id'), table_name='day_notes', schema='planning')
    op.drop_index(op.f('ix_planning_day_notes_day'), table_name='day_notes', schema='planning')
    op.drop_table('day_notes', schema='planning')
    op.drop_index(op.f('ix_notifications_reminders_user_id'), table_name='reminders', schema='notifications')
    op.drop_index(op.f('ix_notifications_reminders_sent'), table_name='reminders', schema='notifications')
    op.drop_index(op.f('ix_notifications_reminders_remind_at'), table_name='reminders', schema='notifications')
    op.drop_index(op.f('ix_notifications_reminders_id'), table_name='reminders', schema='notifications')
    op.drop_table('reminders', schema='notifications')
    op.drop_index(op.f('ix_notifications_notifications_id'), table_name='notifications', schema='notifications')
    op.drop_index(op.f('ix_notifications_notifications_created_by_user_id'), table_name='notifications', schema='notifications')
    op.drop_table('notifications', schema='notifications')
    op.drop_index(op.f('ix_goals_goals_user_id'), table_name='goals', schema='goals')
    op.drop_index(op.f('ix_goals_goals_id'), table_name='goals', schema='goals')
    op.drop_table('goals', schema='goals')
    op.drop_index(op.f('ix_feedback_feedback_messages_user_id'), table_name='feedback_messages', schema='feedback')
    op.drop_index(op.f('ix_feedback_feedback_messages_id'), table_name='feedback_messages', schema='feedback')
    op.drop_table('feedback_messages', schema='feedback')
    op.drop_index(op.f('ix_auth_user_sessions_user_id'), table_name='user_sessions', schema='auth')
    op.drop_index(op.f('ix_auth_user_sessions_jti'), table_name='user_sessions', schema='auth')
    op.drop_index(op.f('ix_auth_user_sessions_id'), table_name='user_sessions', schema='auth')
    op.drop_table('user_sessions', schema='auth')
    op.drop_index(op.f('ix_auth_telegram_links_user_id'), table_name='telegram_links', schema='auth')
    op.drop_index(op.f('ix_auth_telegram_links_link_code'), table_name='telegram_links', schema='auth')
    op.drop_index(op.f('ix_auth_telegram_links_id'), table_name='telegram_links', schema='auth')
    op.drop_index(op.f('ix_auth_telegram_links_chat_id'), table_name='telegram_links', schema='auth')
    op.drop_table('telegram_links', schema='auth')
    op.drop_index(op.f('ix_auth_users_verification_token'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_username'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_id'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_email'), table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    # ### end Alembic commands ###
    for schema in ("auth", "planning", "goals", "notifications", "feedback"):
        op.execute(f'DROP SCHEMA IF EXISTS "{schema}"')
